services:
  backend:
    build:
      context: ./backend
    environment:
      PORT: 2000
      EXTERNAL_API_URL: ${EXTERNAL_API_URL:-https://open.er-api.com/v6/latest/USD}
    ports:
      - '2000:2000'
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - '2002:80'
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
